### ISSUE TITLE
Reproduction of Egoschema results

### ISSUE THREAD

**Issue by Ziyang412** [Agentic-Learning-AI-Lab/lifelong-memory#1]
Hi, thanks for the great work! I am wondering whether you could share the caption.csv file for egoschema dataset for better reproducibility? 

Any help would be highly appreciated!

**Comment by Ziyang412** [comment]
Hi, hope to get reply from the authors. 

I tried to reproduce the code using the caption I extracted using the paper's description, but I got two issue:

1. The success rate of EgoSchema QA is only around 80%, nearly 20% sample cannot process to the output csv. 
2. The accuracy in the successed example is low: on ES subset, only 64.1 Acc using 90 captions, which is lower than the reported numbers.

My reproduction on egoschema fullset is only 54.3 accuracy, which is 13% lower than your kaggle submission. It would be awesome if the authors could give some help on the reproduction. 


Thanks a lot!

**Comment by YingWANGG** [comment]
@Ziyang412 Sorry I didn't see your message earlier. Yes, I also observed that sometimes LLM cannot produce the answer in the correct format (especially for weaker LLMs). For EgoSchema, I simply extracted the first number after "answer" if the output is not a dictionary. In fact, many of these ill-formatted outputs contain correct answers, so you will get a performance boost once fixing the format issue.

**Comment by Ziyang412** [comment]
Hi, thanks a lot for the clarification. Also, could you kindly provide (or point to) the caption that you leveraged in lifelong memory? That would be more than helpful! Appreciate your help!

**Comment by YingWANGG** [comment]
Hi @Ziyang412 The caption link has been added to the repo. It was deleted on our server, so I had to generate it again. Sorry about the delay!

**Comment by Ziyang412** [comment]
Thanks a lot! BTW, may I ask what model version of LaViLA (B or L) are you using for these captions?

**Comment by YingWANGG** [comment]
> Thanks a lot! BTW, may I ask what model version of LaViLA (B or L) are you using for these captions?

I think LaViLa narrator uses TimeSformer-L by default. The model is VCLM_OPENAI_TIMESFORMER_LARGE_336PX_GPT2_XL and chk name is vclm_openai_timesformer_large_336px_gpt2_xl.pt_ego4d.jobid_246897.ep_0003.md5sum_443263.pth

**Comment by Ziyang412** [comment]
Thank you so much for the detailed response, that answers all my question! 

Good luck for your research!
