### ISSUE TITLE
Scripts for Generating the Caption with LLaVA and LaViLa.

### ISSUE THREAD

**Issue by oximi123** [Agentic-Learning-AI-Lab/lifelong-memory#2]
Hi, is it possible to share the scripts for generating the caption using LLaVA and LaViLa, together with the scripts for filtering and merging with ChatGPT 3.5?

**Comment by YingWANGG** [comment]
Hi, we have added the code for caption digest. For generating captions, please refer to the official implementation of [LaViLa](https://github.com/facebookresearch/LaViLa/tree/main), where they have detailed instructions on how to generate narrations.
